{
 "title": "Final",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"
   }
  ]
 },
 "panels": [
  {
   "title": "Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "collection": "readings",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\",\r\n      \"battery_voltage\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"solar\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"pressure\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"battery_voltage\": {\r\n        \"$toDouble\": \"$battery_voltage\"\r\n      },\r\n      \"solar\": {\r\n        \"$toDouble\": \"$solar\"\r\n      },\r\n      \"pressure\": {\r\n        \"$toDouble\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"interval\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$timestamp\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 15\r\n          }\r\n        }\r\n      },\r\n      \"avg_battery_voltage\": {\r\n        \"$avg\": \"$battery_voltage\"\r\n      },\r\n      \"avg_solar\": {\r\n        \"$avg\": \"$solar\"\r\n      },\r\n      \"avg_pressure\": {\r\n        \"$avg\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"_id.interval\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"ts\": \"$_id.interval\",\r\n      \"name\": \"A Pressure\",\r\n      \"value\": {\r\n        \"$toDouble\": {\r\n          \"$divide\": [\r\n            {\r\n              \"$multiply\": [\r\n                {\r\n                  \"$subtract\": [\r\n                    {\r\n                      \"$multiply\": [\r\n                        \"$avg_pressure\",\r\n                        { \"$divide\": [1000, 165] },\r\n                        { \"$divide\": [6.144, 32768] }\r\n                      ]\r\n                    },\r\n                    4\r\n                  ]\r\n                },\r\n                6\r\n              ]\r\n            },\r\n            16\r\n          ]\r\n        }\r\n      }\r\n    }\r\n  }\r\n]"
    },
    {
     "collection": "readings",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\",\r\n      \"battery_voltage\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"solar\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"pressure\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"battery_voltage\": {\r\n        \"$toDouble\": \"$battery_voltage\"\r\n      },\r\n      \"solar\": {\r\n        \"$toDouble\": \"$solar\"\r\n      },\r\n      \"pressure\": {\r\n        \"$toDouble\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"interval\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$timestamp\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 15\r\n          }\r\n        }\r\n      },\r\n      \"avg_battery_voltage\": {\r\n        \"$avg\": \"$battery_voltage\"\r\n      },\r\n      \"avg_solar\": {\r\n        \"$avg\": \"$solar\"\r\n      },\r\n      \"avg_pressure\": {\r\n        \"$avg\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"_id.interval\": 1\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"ts\": \"$_id.interval\",\r\n    \r\n      \"Solar\": {\r\n        \"$toInt\": \"$avg_solar\"\r\n      }\r\n    }\r\n  }\r\n]"
    },
    {
     "collection": "readings",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\",\r\n      \"battery_voltage\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"solar\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"pressure\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"battery_voltage\": {\r\n        \"$toDouble\": \"$battery_voltage\"\r\n      },\r\n      \"solar\": {\r\n        \"$toDouble\": \"$solar\"\r\n      },\r\n      \"pressure\": {\r\n        \"$toDouble\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"interval\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$timestamp\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 15\r\n          }\r\n        }\r\n      },\r\n      \"avg_battery_voltage\": {\r\n        \"$avg\": \"$battery_voltage\"\r\n      },\r\n      \"avg_solar\": {\r\n        \"$avg\": \"$solar\"\r\n      },\r\n      \"avg_pressure\": {\r\n        \"$avg\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$sort\": {\r\n      \"_id.interval\": 1\r\n    }\r\n  },\r\n{\r\n  \"$project\": {\r\n    \"_id\": 0,\r\n    \"ts\": \"$_id.interval\",\r\n    \"Battery Voltage\": {\r\n      \"$multiply\": [\"$avg_battery_voltage\", 0.000867]\r\n    }\r\n  }\r\n}\r\n]"
    }
   ]
  },
  {
   "title": "Location of Nodes",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "collection": "location",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\"\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"node_id\": 1,\r\n      \"latitude\": 1,\r\n      \"longitude\": 1\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "readings",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\",\r\n      \"battery_voltage\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"solar\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"pressure\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"battery_voltage\": {\r\n        \"$toDouble\": \"$battery_voltage\"\r\n      },\r\n      \"solar\": {\r\n        \"$toDouble\": \"$solar\"\r\n      },\r\n      \"pressure\": {\r\n        \"$toDouble\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"interval\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$timestamp\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 5\r\n          }\r\n        }\r\n      },\r\n      \"avg_battery_voltage\": {\r\n        \"$avg\": \"$battery_voltage\"\r\n      },\r\n      \"avg_solar\": {\r\n        \"$avg\": \"$solar\"\r\n      },\r\n      \"avg_pressure\": {\r\n        \"$avg\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n\r\n    {\r\n    \"$project\": {\r\n      \"value\": {\r\n        \"$toDouble\": {\r\n          \"$divide\": [\r\n            {\r\n              \"$multiply\": [\r\n                {\r\n                  \"$subtract\": [\r\n                    {\r\n                      \"$multiply\": [\r\n                        \"$avg_pressure\",\r\n                        { \"$divide\": [1000, 165] },\r\n                        { \"$divide\": [6.144, 32768] }\r\n                      ]\r\n                    },\r\n                    4\r\n                  ]\r\n                },\r\n                6\r\n              ]\r\n            },\r\n            16\r\n          ]\r\n        }\r\n      }\r\n    }\r\n  }\r\n\r\n]"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "readings",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\",\r\n      \"battery_voltage\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"solar\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"pressure\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"battery_voltage\": {\r\n        \"$toDouble\": \"$battery_voltage\"\r\n      },\r\n      \"solar\": {\r\n        \"$toDouble\": \"$solar\"\r\n      },\r\n      \"pressure\": {\r\n        \"$toDouble\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"interval\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$timestamp\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 5\r\n          }\r\n        }\r\n      },\r\n      \"avg_battery_voltage\": {\r\n        \"$avg\": \"$battery_voltage\"\r\n      },\r\n      \"avg_solar\": {\r\n        \"$avg\": \"$solar\"\r\n      },\r\n      \"avg_pressure\": {\r\n        \"$avg\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"value\": {\r\n        \"$multiply\": [\r\n          \"$avg_battery_voltage\",\r\n          0.000867\r\n        ]\r\n      }\r\n    }\r\n    }\r\n  ]"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "collection": "readings",
     "queryLanguage": "json",
     "queryText": "[\r\n  {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\",\r\n      \"battery_voltage\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"solar\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      },\r\n      \"pressure\": {\r\n        \"$exists\": true,\r\n        \"$ne\": null\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$addFields\": {\r\n      \"battery_voltage\": {\r\n        \"$toDouble\": \"$battery_voltage\"\r\n      },\r\n      \"solar\": {\r\n        \"$toDouble\": \"$solar\"\r\n      },\r\n      \"pressure\": {\r\n        \"$toDouble\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n  {\r\n    \"$group\": {\r\n      \"_id\": {\r\n        \"interval\": {\r\n          \"$dateTrunc\": {\r\n            \"date\": \"$timestamp\",\r\n            \"unit\": \"minute\",\r\n            \"binSize\": 5\r\n          }\r\n        }\r\n      },\r\n      \"avg_battery_voltage\": {\r\n        \"$avg\": \"$battery_voltage\"\r\n      },\r\n      \"avg_solar\": {\r\n        \"$avg\": \"$solar\"\r\n      },\r\n      \"avg_pressure\": {\r\n        \"$avg\": \"$pressure\"\r\n      }\r\n    }\r\n  },\r\n\r\n  {\r\n    \"$project\": {\r\n      \"value\": {\r\n        \"$toInt\": \"0\"\r\n      }\r\n    }\r\n  }\r\n]"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "collection": "logs",
     "queryLanguage": "json",
     "queryText": " [\r\n    {\r\n    \"$match\": {\r\n      \"node_id\": \"$node_id\"\r\n    }\r\n  },\r\n  {\r\n    \"$project\": {\r\n      \"_id\": 0,\r\n      \"node_id\": \"$node_id\",\r\n      \"message\": 1,\r\n      \"timestamp\": 1\r\n    }\r\n  }\r\n]\r\n"
    }
   ]
  }
 ]
}